import RolesCheckboxes from "../components/auth/admin/RolesCheckboxes";
import RolePermissions from "../components/auth/admin/RolePermissions";
import CreateEditTeam from "../components/auth/teams/CreateEditTeam";
import TeamMemberCard from "../components/auth/teams/TeamMemberCard";
import CreateEditSettlement from "../components/auth/admin/settlement/CreateEditSettlement";
import CreateEditSport from "../components/auth/admin/sport/CreateEditSport";
import SettlementsList from "../components/auth/admin/settlement/SettlemenstList";
import SportList from "../components/auth/admin/sport/SportList";
import ToggleActivationButton from "../components/auth/buttons/ToggleActivationButton";
import DistributeUsersList from "../components/auth/distribution/DistributeUsersList";

Vue.component('roles-checkboxes', RolesCheckboxes);
Vue.component('roles-permissions', RolePermissions);
Vue.component('create-edit-team', CreateEditTeam);
Vue.component('team-member-card', TeamMemberCard);
Vue.component('create-edit-settlement', CreateEditSettlement);
Vue.component('create-edit-sport', CreateEditSport);
Vue.component('settlements-list', SettlementsList);
Vue.component('sport-list', SportList);
Vue.component('toggle-activation-button', ToggleActivationButton);
Vue.component('distribute-users-list', DistributeUsersList);